export const ROUTE_NAMES = {
    HOME: 'home',
    AUTH: 'auth',
    CHECKLISTS: 'checklists',
    USER: 'user',
    USER_EDIT: 'userEdit',
    SETTINGS: 'settings',
    USERS: 'users',
    PANEL: 'panel',
    TEST: 'test',
    PROFILE: 'profile',
    NOT_FOUND: 'notfound',
    CALENDAR: 'calendar',
    ARTICLES: 'articles',
    ARTICLES_EDIT: 'articlesEdit',
    ARTICLES_CREATE: 'articlesCreate',
    ARTICLES_SINGLE: 'articlesSingle',
    ANIMATIONS: 'animations',
    STATEMENTS: 'statements',
    STATEMENTS_PROCESSING: 'statementsProcessing',
    SUPPORT: 'support',
    SUPPORT_TICKET: 'supportTicket',
    UI_KIT: 'ui-kit',
    CHAT: 'chat',
    CHAT_ID: 'chat-id'
};